---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over neutron.conf
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/neutron.conf.j2"
#      - "{{ role_path }}/templates/neutron.conf.j2"
#      - "{{ node_custom_config }}/neutron.conf"
#      - "{{ node_custom_config }}/neutron/{{ item }}.conf"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/{{ item }}/neutron.conf"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over ml2_conf.ini
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/ml2_conf.ini.j2"
#      - "{{ role_path }}/templates/ml2_conf.ini.j2"
#      - "{{ node_custom_config }}/neutron/ml2_conf.ini"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/ml2_conf.ini"
    dest: "{{ node_config_directory }}/{{ item }}/ml2_conf.ini"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over ml2_conf_cisco.ini
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/ml2_conf_cisco.ini.j2"
#      - "{{ role_path }}/templates/ml2_conf_cisco.ini.j2"
#      - "{{ node_custom_config }}/neutron/ml2_conf_cisco.ini"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/ml2_conf_cisco.ini"
    dest: "{{ node_config_directory }}/{{ item }}/ml2_conf_cisco.ini"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"


- name: Copying over neutron-dist.conf
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/neutron-dist.conf.j2"
#      - "{{ role_path }}/templates/neutron-dist.conf.j2"
#      - "{{ node_custom_config }}/neutron/neutron-dist.conf"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron-dist.conf"
    dest: "{{ node_config_directory }}/{{ item }}/neutron-dist.conf"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over ovs_neutron_plugin.ini
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/ovs_neutron_plugin.ini.j2"
#      - "{{ role_path }}/templates/ovs_neutron_plugin.ini.j2"
#      - "{{ node_custom_config }}/neutron/ovs_neutron_plugin.ini"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/ovs_neutron_plugin.ini"
    dest: "{{ node_config_directory }}/{{ item }}/ovs_neutron_plugin.ini"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over opflex-agent-ovs.conf
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/opflex-agent-ovs.conf.j2"
#      - "{{ role_path }}/templates/opflex-agent-ovs.conf.j2"
#      - "{{ node_custom_config }}/neutron/opflex-agent-ovs.conf"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/opflex-agent-ovs.conf"
    dest: "{{ node_config_directory }}/{{ item }}/opflex-agent-ovs.conf"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over metadata.conf
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/metadata.conf.j2"
#      - "{{ role_path }}/templates/metadata.conf.j2"
#      - "{{ node_custom_config }}/neutron/metadata.conf"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/metadata.conf"
    dest: "{{ node_config_directory }}/{{ item }}/metadata.conf"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"

- name: Copying over metadata_agent.ini
#  merge_configs:
#    vars:
#      service_name: "{{ item }}"
#    sources:
  template:
    src: "{{ role_path }}/templates/metadata_agent.ini.j2"
#      - "{{ role_path }}/templates/metadata_agent.ini.j2"
#      - "{{ node_custom_config }}/neutron/metadata_agent.ini"
#      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/metadata_agent.ini"
    dest: "{{ node_config_directory }}/{{ item }}/metadata_agent.ini"
  with_items:
    - "gbp-neutron-server"
    - "gbp-agent-ovs"
    - "gbp-opflex-agent"
